### PR TITLE
Added onResizeHandleDoubleClick  Callback 

### PR DESCRIPTION
**Pull request by ripitrust**
Added onResizeHandleDoubleClick callback that allows customised action when double clicking the resize handler ( Such as Auto-sizing, Fit to Content).
May be useful to some people

### CODE REVIEW

**Comment by Robsonsjre** [comment]
+ 1

**Comment by gamedevsam** [comment]
I would love to see this go in.

**Comment by ripitrust** [comment]
Hi @gamedevsam  

Thanks for the interest

You may checkout my fork of this library https://github.com/ripitrust/fixed-data-table

**Comment by zpao** [comment]
Thanks for your pull request. I apologize for leaving this project in limbo and not addressing your concerns. I have archived this project after doing a final release to make it compatible with React v16.

**Pull request closed without merging**
