### PR TITLE
added a bower.json file

### PR DESCRIPTION
**Pull request by allanbond**
I'm not seeing a bower.json file in the source. Here's a minimal one that will allow devs to pull fixed-data-table into their own projects.

### CODE REVIEW

**Comment by pieterv** [comment]
Hey @allanbond shouldn't it be enough to install via `bower install facebook/fixed-data-table` and reference the dist files? What advantage does having the bower.json file give? Bower can look at git tags right?

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by kursion** [comment]
The bower.json file will be needed. If the package doesn't respect the standard of bower it will not be possible to guess what is the "entry point" or "main" file.

**Comment by cesarandreu** [comment]
[Why We Should Stop Using Bower – And How to Do It](http://gofore.com/ohjelmistokehitys/stop-using-bower/)

**Comment by kursion** [comment]
I'm not 100% convinced by this article. Even if it has some good arguments, the usability and the simplicity to manage small to big projects is pretty strong with bower. It is pretty stable and offer decent tools (integrated watcher, auto-reload, cache compilation, map files, ...). You'll need a lot of tools to imitate bower.

**Comment by cesarandreu** [comment]
@kursion You want npm and [webpack](http://webpack.github.io/). Webpack solve all those problems correctly. AFAIK, bower doesn't have any of those things you mentioned either.

**Comment by kursion** [comment]
Well it seems that you didn't tested it in depth. It has all the mentioned tools (and more), and I'm using them everyday...

http://brunch.io/compare.html

Anyway doesn't seem to be the right place to battle on that topic. Wepack with NPM is great too, but bower is far from being useless and bad ;)

**Comment by zpao** [comment]
Thanks for your pull request. I apologize for leaving this project in limbo and not addressing your concerns. I have archived this project after doing a final release to make it compatible with React v16.

**Pull request closed without merging**
