### PR TITLE
Implement column reordering

### PR DESCRIPTION
**Pull request by stutrek**
This adds support for drag and drop column reordering, adds and example, and updates the docs. It is used just like column resizing, with a `onColumnReorderEndCallback` passed as a prop to the table.
- http://stutrek.github.io/fixed-data-table/example-reorder.html
- https://github.com/stutrek/fixed-data-table/blob/master/examples/ReorderExample.js#L58-L71

_note: I am ignoring the directive not to edit the dist folder because I actually need to use this._

If you're trying to use this you can include it the normal npm way and add this to your webpack config:

``` javascript
  alias: {
    'fixed-data-table$': __dirname + '/node_modules/fixed-data-table/dist/fixed-data-table'
  }
```

### CODE REVIEW

**Comment by JMacLulich** [comment]
This is great, thanks @stutrek  exactly what I was looking for, is there any chance this PR can make it into master?

**Comment by stutrek** [comment]
@JMacLulich I think you're going to want this branch, it's much better. I haven't had time to close this PR and make a new one yet.

https://github.com/stutrek/fixed-data-table/tree/f/better-reorder

**Comment by KamranAsif** [comment]
@wcjordan can we get a ticket to bring over these commits?

**Comment by stutrek** [comment]
I just rebased

**Comment by zpao** [comment]
Thanks for your pull request. I apologize for leaving this project in limbo and not addressing your concerns. I have archived this project after doing a final release to make it compatible with React v16.

**Pull request closed without merging**
